# Generated by Django 3.2.10 on 2022-01-04 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marketing_reg_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('target', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recruitments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobpostname', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('vacancies', models.IntegerField()),
                ('qualifications', models.CharField(max_length=200)),
                ('jobdescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TL_recr_to_datacollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketingapp.marketing_reg_details')),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketingapp.recruitments')),
            ],
        ),
        migrations.CreateModel(
            name='TL_prod_to_datacollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketingapp.marketing_reg_details')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketingapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='prod_datacollected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phno', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
                ('exec_assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='marketingapp.marketing_reg_details')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketingapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='jobapplicant_datacollected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phno', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('fresher_or_exp', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
                ('exec_assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='marketingapp.marketing_reg_details')),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketingapp.recruitments')),
            ],
        ),
        migrations.CreateModel(
            name='hr_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField()),
                ('reported_date', models.DateField()),
                ('hr_reply', models.TextField()),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketingapp.marketing_reg_details')),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=200)),
                ('logintime', models.CharField(max_length=200)),
                ('logouttime', models.CharField(max_length=200)),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketingapp.marketing_reg_details')),
            ],
        ),
    ]
